/**
  * @author Romain & Jennifer
 */
package battleship.frame;

import javax.swing.JFrame;

public class GameFrame extends JFrame
{
	static final long serialVersionUID=0;
	    /**
	     * Creates new form GameFrame
	     */
	    public GameFrame() {
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings({ "unchecked", "rawtypes" })
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jMenuItem1 = new javax.swing.JMenuItem();
	        jDialog1 = new javax.swing.JDialog();
	        T_gamePanel = new javax.swing.JTabbedPane();
	        T_placeBoard = new javax.swing.JTabbedPane();
	        jSplitPane1 = new javax.swing.JSplitPane();
	        jScrollPane2 = new javax.swing.JScrollPane();
	        G_yourships = new javax.swing.JTable();
	        jScrollPane3 = new javax.swing.JScrollPane();
	        L_ships = new javax.swing.JList();
	        t_waiting = new javax.swing.JTabbedPane();
	        jPanel2 = new javax.swing.JPanel();
	        jLabel3 = new javax.swing.JLabel();
	        t_gameinrun = new javax.swing.JTabbedPane();
	        jPanel1 = new javax.swing.JPanel();
	        jPanel3 = new javax.swing.JPanel();
	        jScrollPane6 = new javax.swing.JScrollPane();
	        G_Radar = new javax.swing.JTable();
	        B_fire = new javax.swing.JToggleButton();
	        l_Sopponent = new javax.swing.JLabel();
	        jScrollPane7 = new javax.swing.JScrollPane();
	        G_yourship = new javax.swing.JTable();
	        jScrollPane4 = new javax.swing.JScrollPane();
	        TA_gamelog = new javax.swing.JTextArea();
	        l_gamelog = new javax.swing.JLabel();
	        l_userShip = new javax.swing.JLabel();
	        t_rorquit = new javax.swing.JTabbedPane();
	        T_chooseend = new javax.swing.JPanel();
	        B_revenge = new javax.swing.JButton();
	        B_quit = new javax.swing.JToggleButton();
	        l_revenge = new javax.swing.JLabel();
	        jSeparator1 = new javax.swing.JSeparator();
	        l_playersin = new javax.swing.JLabel();
	        jScrollPane1 = new javax.swing.JScrollPane();
	        l_playerin = new javax.swing.JList();
	        l_vertical = new javax.swing.JLabel();
	        c_verticale = new javax.swing.JCheckBox();

	        jMenuItem1.setText("jMenuItem1");

	        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
	        jDialog1.getContentPane().setLayout(jDialog1Layout);
	        jDialog1Layout.setHorizontalGroup(
	            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGap(0, 400, Short.MAX_VALUE)
	        );
	        jDialog1Layout.setVerticalGroup(
	            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGap(0, 300, Short.MAX_VALUE)
	        );

	        G_yourships.setModel(new javax.swing.table.DefaultTableModel(
	            new Object [][] {
	                {null, null, null, null},
	                {null, null, null, null},
	                {null, null, null, null},
	                {null, null, null, null}
	            },
	            new String [] {
	                "Title 1", "Title 2", "Title 3", "Title 4"
	            }
	        ));
	        jScrollPane2.setViewportView(G_yourships);

	        jSplitPane1.setRightComponent(jScrollPane2);

	        L_ships.setModel(new javax.swing.AbstractListModel() {
	            /**
				 * 
				 */
				private static final long serialVersionUID = 1L;
				String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
	            public int getSize() { return strings.length; }
	            public Object getElementAt(int i) { return strings[i]; }
	        });
	        jScrollPane3.setViewportView(L_ships);

	        jSplitPane1.setLeftComponent(jScrollPane3);

	        T_placeBoard.addTab("tab1", jSplitPane1);

	        T_gamePanel.addTab("Set your borad places", T_placeBoard);

	        jLabel3.setText("Wainting for your opponent.");

	        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
	        jPanel2.setLayout(jPanel2Layout);
	        jPanel2Layout.setHorizontalGroup(
	            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel2Layout.createSequentialGroup()
	                .addGap(138, 138, 138)
	                .addComponent(jLabel3)
	                .addContainerGap(155, Short.MAX_VALUE))
	        );
	        jPanel2Layout.setVerticalGroup(
	            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel2Layout.createSequentialGroup()
	                .addGap(101, 101, 101)
	                .addComponent(jLabel3)
	                .addContainerGap(178, Short.MAX_VALUE))
	        );

	        t_waiting.addTab("tab1", jPanel2);

	        T_gamePanel.addTab("Wait", t_waiting);

	        G_Radar.setModel(new javax.swing.table.DefaultTableModel(
	            new Object [][] {
	                {null, null, null, null},
	                {null, null, null, null},
	                {null, null, null, null},
	                {null, null, null, null}
	            },
	            new String [] {
	                "Title 1", "Title 2", "Title 3", "Title 4"
	            }
	        ));
	        jScrollPane6.setViewportView(G_Radar);

	        B_fire.setText("Fire!");
	        B_fire.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                B_fireActionPerformed(evt);
	            }
	        });

	        l_Sopponent.setText("Opponent Ship Field");

	        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
	        jPanel3.setLayout(jPanel3Layout);
	        jPanel3Layout.setHorizontalGroup(
	            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel3Layout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(B_fire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                    .addGroup(jPanel3Layout.createSequentialGroup()
	                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(l_Sopponent))
	                        .addGap(0, 0, Short.MAX_VALUE)))
	                .addContainerGap())
	        );
	        jPanel3Layout.setVerticalGroup(
	            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel3Layout.createSequentialGroup()
	                .addContainerGap(24, Short.MAX_VALUE)
	                .addComponent(l_Sopponent)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(B_fire))
	        );

	        G_yourship.setModel(new javax.swing.table.DefaultTableModel(
	            new Object [][] {
	                {null, null, null, null},
	                {null, null, null, null},
	                {null, null, null, null},
	                {null, null, null, null}
	            },
	            new String [] {
	                "Title 1", "Title 2", "Title 3", "Title 4"
	            }
	        ));
	        jScrollPane7.setViewportView(G_yourship);

	        TA_gamelog.setColumns(20);
	        TA_gamelog.setRows(5);
	        jScrollPane4.setViewportView(TA_gamelog);

	        l_gamelog.setText("Game Log");

	        l_userShip.setText("Your Ship");

	        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	        jPanel1.setLayout(jPanel1Layout);
	        jPanel1Layout.setHorizontalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jPanel1Layout.createSequentialGroup()
	                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
	                        .addContainerGap())
	                    .addGroup(jPanel1Layout.createSequentialGroup()
	                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(l_gamelog)
	                            .addComponent(l_userShip))
	                        .addGap(0, 0, Short.MAX_VALUE))))
	        );
	        jPanel1Layout.setVerticalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(13, Short.MAX_VALUE))
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(l_gamelog)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(l_userShip)
	                .addGap(8, 8, 8)
	                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
	        );

	        t_gameinrun.addTab("tab1", jPanel1);

	        T_gamePanel.addTab("Game", t_gameinrun);

	        B_revenge.setText("Revenge!");
	        B_revenge.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                B_revengeActionPerformed(evt);
	            }
	        });

	        B_quit.setText("Quit");

	        l_revenge.setText("Revenge?");

	        javax.swing.GroupLayout T_chooseendLayout = new javax.swing.GroupLayout(T_chooseend);
	        T_chooseend.setLayout(T_chooseendLayout);
	        T_chooseendLayout.setHorizontalGroup(
	            T_chooseendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(T_chooseendLayout.createSequentialGroup()
	                .addGap(22, 22, 22)
	                .addGroup(T_chooseendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(l_revenge)
	                    .addGroup(T_chooseendLayout.createSequentialGroup()
	                        .addComponent(B_revenge, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(18, 18, 18)
	                        .addComponent(B_quit, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                .addContainerGap(20, Short.MAX_VALUE))
	        );
	        T_chooseendLayout.setVerticalGroup(
	            T_chooseendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(T_chooseendLayout.createSequentialGroup()
	                .addGap(68, 68, 68)
	                .addComponent(l_revenge)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(T_chooseendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(B_revenge)
	                    .addComponent(B_quit))
	                .addContainerGap(177, Short.MAX_VALUE))
	        );

	        t_rorquit.addTab("tab1", T_chooseend);

	        T_gamePanel.addTab("Revenge? Or Quit", t_rorquit);

	        l_playersin.setText("Players-In");

	        l_playerin.setModel(new javax.swing.AbstractListModel() {
	            /**
				 * 
				 */
				private static final long serialVersionUID = 1L;
				String[] strings = { "Item 1", "Item 2" };
	            public int getSize() { return strings.length; }
	            public Object getElementAt(int i) { return strings[i]; }
	        });
	        jScrollPane1.setViewportView(l_playerin);

	        l_vertical.setText("Verticale?");

	        c_verticale.setText("jCheckBox1");

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	        this.setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jSeparator1)
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(T_gamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jScrollPane1)
	                            .addGroup(layout.createSequentialGroup()
	                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addComponent(l_playersin, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                    .addComponent(l_vertical)
	                                    .addComponent(c_verticale))
	                                .addGap(0, 10, Short.MAX_VALUE)))))
	                .addContainerGap())
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                .addGap(48, 48, 48)
	                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                        .addComponent(T_gamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
	                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
	                        .addGap(40, 40, 40)
	                        .addComponent(l_playersin, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(18, 18, 18)
	                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(18, 18, 18)
	                        .addComponent(l_vertical)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addComponent(c_verticale)))
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );
	    }// </editor-fold>                        

	    private void B_revengeActionPerformed(java.awt.event.ActionEvent evt) {                                          
	        // TODO add your handling code here:
	    }                                         

	    private void B_fireActionPerformed(java.awt.event.ActionEvent evt) {                                       
	        // TODO add your handling code here:
	    }                                      


	    // Variables declaration - do not modify                     
	    private javax.swing.JToggleButton B_fire;
	    private javax.swing.JToggleButton B_quit;
	    private javax.swing.JButton B_revenge;
	    private javax.swing.JTable G_Radar;
	    private javax.swing.JTable G_yourship;
	    private javax.swing.JTable G_yourships;
	    @SuppressWarnings("rawtypes")
		private javax.swing.JList L_ships;
	    private javax.swing.JTextArea TA_gamelog;
	    private javax.swing.JPanel T_chooseend;
	    private javax.swing.JTabbedPane T_gamePanel;
	    private javax.swing.JTabbedPane T_placeBoard;
	    private javax.swing.JCheckBox c_verticale;
	    private javax.swing.JDialog jDialog1;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JMenuItem jMenuItem1;
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JPanel jPanel2;
	    private javax.swing.JPanel jPanel3;
	    private javax.swing.JScrollPane jScrollPane1;
	    private javax.swing.JScrollPane jScrollPane2;
	    private javax.swing.JScrollPane jScrollPane3;
	    private javax.swing.JScrollPane jScrollPane4;
	    private javax.swing.JScrollPane jScrollPane6;
	    private javax.swing.JScrollPane jScrollPane7;
	    private javax.swing.JSeparator jSeparator1;
	    private javax.swing.JSplitPane jSplitPane1;
	    private javax.swing.JLabel l_Sopponent;
	    private javax.swing.JLabel l_gamelog;
	    @SuppressWarnings("rawtypes")
		private javax.swing.JList l_playerin;
	    private javax.swing.JLabel l_playersin;
	    private javax.swing.JLabel l_revenge;
	    private javax.swing.JLabel l_userShip;
	    private javax.swing.JLabel l_vertical;
	    private javax.swing.JTabbedPane t_gameinrun;
	    private javax.swing.JTabbedPane t_rorquit;
	    private javax.swing.JTabbedPane t_waiting;
	    // End of variables declaration                   
	}
