package battleship.gamepanel;

//import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

	public class ConnectPanel extends javax.swing.JPanel implements ActionListener{
		static final long serialVersionUID=0;


	    // Variables declaration - do not modify                     
	    private javax.swing.JButton B_joinServer;
	    private javax.swing.JButton B_quit;
	    private javax.swing.JTextField TF_username;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel l_enterUsername;
	    // End of variables declaration     
	    
	    /**
	     * Creates new form ConnectPanel
	     */
	    public ConnectPanel() {
	        initComponents();
	    }
	    
	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        l_enterUsername = new javax.swing.JLabel();
	        TF_username = new javax.swing.JTextField();
	        B_joinServer = new javax.swing.JButton();
	        B_quit = new javax.swing.JButton();
	        jLabel1 = new javax.swing.JLabel();

	        l_enterUsername.setText("Enter your nickname");
	        l_enterUsername.setFocusable(false);

	        TF_username.setText("jTextField1");
	        TF_username.addFocusListener(new java.awt.event.FocusAdapter() {
	            public void focusGained(java.awt.event.FocusEvent evt) {
	                TF_usernameFocusGained(evt);
	            }
	        });
	        TF_username.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                TF_usernameActionPerformed(evt);
	            }
	        });

	        B_joinServer.setText("Join the Server");
	        B_joinServer.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                B_joinServerActionPerformed(evt);
	            }
	        });

	        B_quit.setText("Quit this session");

	        jLabel1.setText("You going to join a game server to play a BattleShip Game online : ");

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	        this.setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(l_enterUsername)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                            .addGroup(layout.createSequentialGroup()
	                                .addComponent(B_joinServer, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(B_quit))
	                            .addComponent(TF_username)))
	                    .addComponent(jLabel1))
	                .addContainerGap(23, Short.MAX_VALUE))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jLabel1)
	                .addGap(18, 18, 18)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(l_enterUsername)
	                    .addComponent(TF_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(B_joinServer)
	                    .addComponent(B_quit))
	                .addContainerGap(55, Short.MAX_VALUE))
	        );
	    }// </editor-fold>                        

	    private void B_joinServerActionPerformed(java.awt.event.ActionEvent evt) {                                             
	        // TODO add your handling code here:
	    }                                            

	    private void TF_usernameFocusGained(java.awt.event.FocusEvent evt) {                                        
	        // TODO add your handling code here:
	    }                                       

	    private void TF_usernameActionPerformed(java.awt.event.ActionEvent evt) {                                            
	        // TODO add your handling code here:
	    }                                                         
	
	public void actionPerformed(ActionEvent e) { 
		
		if(e.getSource() == B_joinServer) {
			//player1.setUserName(TF_username.getText());
		}

	}
}
